{% set name = "gwosc" %}
{% set version = "0.5.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fec6a652bfb12db99aabdaae0639e1a4d957d68e4405702cb7a8fb77dfa3df3e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - requests

test:
  requires:
    - pytest
    - requests-mock >=1.5.0
  imports:
    - gwosc
  commands:
    - python -m pytest --pyargs {{ name }} -m "not remote"

about:
  home: https://pypi.org/project/gwosc/
  dev_url: https://github.com/gwpy/gwosc
  doc_url: https://gwosc.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python interface to the GW Open Science data archive
  description: |
    The `gwosc` package provides an interface to querying the open data
    releases hosted on <https://gw-openscience.org> from the LIGO and Virgo
    gravitational-wave observatories.

extra:
  recipe-maintainers:
    - duncanmmacleod
