{% set name = "gwosc" %}
{% set version = "0.5.2" %}
{% set sha256 = "b78b27c17d524da8dc15d28277d9ab073e25eb5fc0866cbc31635f7a1d6fc88a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - gwosc
  commands:
    - python -m pytest --pyargs {{ name }} -m "not remote"

about:
  home: https://pypi.org/project/gwosc/
  dev_url: https://github.com/gwpy/gwosc
  doc_url: https://gwosc.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python interface to the GW Open Science data archive
  description: |
    The `gwosc` package provides an interface to querying the open data
    releases hosted on <https://losc.ligo.org> from the LIGO and Virgo
    gravitational-wave observatories.

extra:
  recipe-maintainers:
    - duncanmmacleod
