{% set name = "gwosc" %}
{% set version = "0.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4a890147ffbd76bfa800f6d01dd614cfb85b7623c537b93d713656144a9edff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.2.5
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - requests >=1.0.0

test:
  requires:
    - pip
    - pytest
    - requests-mock >=1.5.0
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show gwosc
    # run unit tests
    - python -m pytest --pyargs {{ name }} -m "not remote"

about:
  home: https://pypi.org/project/gwosc/
  dev_url: https://github.com/gwpy/gwosc.git
  doc_url: https://gwosc.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python interface to the GW Open Science data archive
  description: |
    The `gwosc` package provides an interface to querying the open data
    releases hosted on <https://gw-openscience.org> from the LIGO and Virgo
    gravitational-wave observatories.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - martinberoiz
