{% set name = "gwosc" %}
{% set version = "0.3.4" %}
{% set sha256 = "18ed53e2b0260bc2f41bfebcc196465081d97b92860b7083e321f9c39fb98ee2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six

test:
  requires:
    - pytest
  imports:
    - gwosc
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: https://gwosc.readthedocs.io
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A python interface to the GW Open Science data archive
  description: |
    The `gwosc` package provides an interface to querying the open data
    releases hosted on <https://losc.ligo.org> from the LIGO and Virgo
    gravitational-wave observatories.

extra:
  recipe-maintainers:
    - duncanmmacleod
