{% set name = "gwosc" %}
{% set version = "0.5.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 152a505d0a858c789c8ba30b05ec3d5874c6de7bafda1cc4919fc9763b77595a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=38.2.5
    - setuptools-scm
  run:
    - python >=3.5
    - requests >=1.0.0

test:
  requires:
    - pip
    - pytest
    - requests-mock >=1.5.0
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest --pyargs {{ name }} -m "not remote"

about:
  home: https://pypi.org/project/gwosc/
  dev_url: https://github.com/gwpy/gwosc.git
  doc_url: https://gwosc.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python interface to the GW Open Science data archive
  description: |
    The `gwosc` package provides an interface to querying the open data
    releases hosted on <https://gw-openscience.org> from the LIGO and Virgo
    gravitational-wave observatories.

extra:
  recipe-maintainers:
    - duncanmmacleod
