travis:
  secure:
    BINSTAR_TOKEN: SSw+aHcBkFNBVSe+n2VMKUKJPTGBTvdyhyrZeofusd9aS0t+SexOEUZxIUbzjy30SH1o2CtxtMDED0uq3ubul427ahmAbQ1kQ5ckYsmi2+kZsi2jFevYTjSyRgFYKXY4TyHGmU5kaeMVyDFA/gBPElUZkI7mlQ3znolDqfw3JVNo0mKaX7gpGVhJEaJXzvL/+cx64FUYjICYZzJEWh4u/UZ41vLlf4zDQx1T4aR8/5FgXKfCAosq6VBueNPYDFRsIyQh7KiEunDIz1F8pfndymPjMVimx8gwRNjC7jyZuZf9OAVBVlEx7d5982rDpuBr21e2s8V6v2SnDY2KQf/g1XvX7prEk0+l3MkeLjOJUSbIx/1/+qMpsYZylZV0KdzKlC9oMuo/EVxT3eRtJq+DWut9072TBM40ciCLukIWEG3sz2jTbjx4Vdbg4qhlA4XGQn6ezkXZdJ9bXL331aDCrXc7U3FimQBwaFZ92i3Zj61lmmVbr19t9sSr7Y53PUYOuI8lrMToOp1GxP9IMaccJx4Zvh52aV6T9m4Yt7wf/TN4DB8Sg3a542LfGX8IQH8kEJECTa0lMOU/UC4X5+Q6uxF0qnQE6125B4Ra32Sx47EUUQE3V/GZcKmgjPsAXIudWddGAYHoAEKzGU44q92R1LOVpTRRyWeVqgrFJRN3zdY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
