travis:
  secure:
    BINSTAR_TOKEN: BFFf02e3/fs39DHw7gSjDit0KwJ9idAeDddzZ1EsIXVOLN2j+QPdrx25WTws6/tGrcNopnts7bBw1JHl4qLIZ2s7fXsuOVnxR62kI5J68t5vDUn863f/Tg88wuCaOtQSDRVm4ztyWwh5Jl6VvjjEabXAVMgKpk2v+gwWJxWJXDk80KeQUztGb/iKz2LTWaario5M6CH0nklMNr4auxG69QQrQquu2bu4HZoGQWnF26e2x+GYTZaY9XjJbP9peR2QTOZHRrEJJemF12WYaNBHCzuWRAI04NZ1SBH4vRNm3fEgttgC9OIOXSiG+/bMfkmEFOBgJ3q7VnsEZZEJLov503GO/ICpoMpun3TxJv7WKdDsfQbmBf4DD4GRckWE8ig9FsCXfx6oKA8q2+dm5Wd01/wsQbaZQddR6ZblTurao4QJCCcuje1+V+ushUeOJwd6RTaDweMFTW3mch7QMihu/V9s7yOZISK/qzkebFPk/5B+mWkW5lV3SaiQzPO8msfTDm1xJ4g7/gblsYkamXVu2iEfcDhY7o1+nrMlNRgtuRCUj6ilgiuvgXyy4syGeQyxDZVJNf5FHROqwb57wcW1PgGRNdQbZ86EcRdoMfSiVUyCKHmGMYqJcbPlv8Kb4OFJUzgQFqYoSXfx/c1b6I2HN9be5JutTefl7SJanYsEsWY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
